version: '3'

services:

  flatfinder:
    image: node:10
    depends_on:
      - chromeless
    env_file: .env
    environment:
      - CHROME_HOST=chromeless
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - ff_network
    command: npm run send

  chromeless:
    image: browserless/chrome
    shm_size: 1g
    expose:
      - "3000"
    networks:
      - ff_network

networks:
  ff_network:
    driver: bridge
